### ISSUE TITLE
ReadFlash returns wrong range

### ISSUE THREAD

**Issue by kukkerman** [pilotak/python-mcp2221#1]
`ReadFlash` method returns wrong range of bytes in the following cases: `FLASH.USB_MANUFACTURER`, `FLASH.USB_PRODUCT_DESCRIPTOR`, `FLASH.USB_SERIAL_NUMBER`. It returns the range `[3:(3+buf[2])]` but the correct one would be `[4:(4+buf[2]-2)]` according to the datasheet.

**Comment by pilotak** [comment]
You are right! thanks for spotting the bug. I have pushed the fix into master branch, could you please try it before releasing? i tested locally and it works fine, but just in case...
